### ISSUE TITLE
Unable to pull image

### ISSUE THREAD

**Issue by alex27riva** [MrKsey/i2pd#1]
Hi, I'm unable to pull the image:
`$ docker pull ksey/i2pd`
```
Using default tag: latest
Error response from daemon: pull access denied for ksey/i2pd, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```

**Comment by MrKsey** [comment]
> Hi, I'm unable to pull the image: `$ docker pull ksey/i2pd`
> 
> ```
> Using default tag: latest
> Error response from daemon: pull access denied for ksey/i2pd, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> ```

Hi. I fixed it. Try again please
